// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/anashasan/goqueue/pkg/api/handlers"
	"github.com/anashasan/goqueue/pkg/application/enqueuer"
	"github.com/anashasan/goqueue/pkg/application/inspector"
	"github.com/anashasan/goqueue/pkg/application/processor"
	"github.com/anashasan/goqueue/pkg/application/services"
	"github.com/anashasan/goqueue/pkg/common/clock"
	"github.com/anashasan/goqueue/pkg/common/logger"
	"github.com/anashasan/goqueue/pkg/common/uid"
	"github.com/anashasan/goqueue/pkg/domain/metrics"
	"github.com/anashasan/goqueue/pkg/domain/persistence"
	"github.com/anashasan/goqueue/pkg/infrastructure/config"
	prometheus2 "github.com/anashasan/goqueue/pkg/infrastructure/metrics/prometheus"
	redis2 "github.com/anashasan/goqueue/pkg/infrastructure/persistence/redis"
	"github.com/anashasan/goqueue/pkg/infrastructure/scheduler"
	"github.com/anashasan/goqueue/pkg/infrastructure/worker"
	"github.com/google/wire"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// ProvideClock provides the wall clock.
func ProvideClock() clock.Clock {
	systemClock := clock.NewSystemClock()
	return systemClock
}

// ProvideUIDGenerator provides the identifier generator.
func ProvideUIDGenerator() uid.Generator {
	randomGenerator := uid.NewRandomGenerator()
	return randomGenerator
}

// ProvideLogger provides the structured logger.
func ProvideLogger(cfg *config.AppConfig) logger.Logger {
	logLevel := config.GetLogLevel(cfg)
	slogLogger := provideSlogLogger(logLevel)
	return slogLogger
}

// ProvideMetricsRegistry provides the Prometheus registry.
func ProvideMetricsRegistry() *prometheus.Registry {
	registry := prometheus2.NewRegistry()
	return registry
}

// ProvideMetricsRecorder provides the metrics port implementation.
func ProvideMetricsRecorder(registry *prometheus.Registry) metrics.Recorder {
	registerer := provideRegisterer(registry)
	recorder := prometheus2.NewRecorder(registerer)
	return recorder
}

// ProvideRedisClient provides the Redis connection.
func ProvideRedisClient(ctx context.Context, cfg *config.AppConfig) (redis.UniversalClient, error) {
	clientConfig := config.GetRedisClientConfig(cfg)
	universalClient, err := redis2.NewClient(ctx, clientConfig)
	if err != nil {
		return nil, err
	}
	return universalClient, nil
}

// ProvideKeyBuilder provides the Redis key layout.
func ProvideKeyBuilder(cfg *config.AppConfig) *redis2.KeyBuilder {
	redisNamespace := config.GetRedisNamespace(cfg)
	keyBuilder := provideKeyBuilder(redisNamespace)
	return keyBuilder
}

// InjectHandlers builds the full HTTP handler graph.
func InjectHandlers(cfg *config.AppConfig, client redis.UniversalClient, recorder metrics.Recorder, registry services.IHandlerRegistry) *handlers.Handlers {
	redisNamespace := config.GetRedisNamespace(cfg)
	keyBuilder := provideKeyBuilder(redisNamespace)
	systemClock := clock.NewSystemClock()
	jobBroker := redis2.NewJobBroker(client, keyBuilder, systemClock)
	idempotencyStore := redis2.NewIdempotencyStore(client, keyBuilder)
	jobRepo := redis2.NewJobRepo(client, keyBuilder, systemClock)
	randomGenerator := uid.NewRandomGenerator()
	logLevel := config.GetLogLevel(cfg)
	slogLogger := provideSlogLogger(logLevel)
	enqueuerConfig := config.GetEnqueuerConfig(cfg)
	enqueuerService := enqueuer.NewEnqueuerService(jobBroker, idempotencyStore, jobRepo, randomGenerator, systemClock, slogLogger, enqueuerConfig)
	queueRepo := redis2.NewQueueRepo(client, keyBuilder)
	inspectorService := inspector.NewInspectorService(jobRepo, queueRepo, jobBroker, systemClock, slogLogger)
	jobHandler := handlers.NewJobHandler(enqueuerService, inspectorService)
	queueHandler := handlers.NewQueueHandler(inspectorService)
	serverVersion := config.GetServerVersion(cfg)
	supportHandler := provideSupportHandler(registry, serverVersion)
	dashboardHandler := handlers.NewDashboardHandler()
	handlersHandlers := handlers.NewHandlers(jobHandler, queueHandler, supportHandler, dashboardHandler)
	return handlersHandlers
}

// InjectWorkerPool builds the worker pool graph.
func InjectWorkerPool(cfg *config.AppConfig, client redis.UniversalClient, recorder metrics.Recorder, registry services.IHandlerRegistry) *worker.Pool {
	redisNamespace := config.GetRedisNamespace(cfg)
	keyBuilder := provideKeyBuilder(redisNamespace)
	systemClock := clock.NewSystemClock()
	jobBroker := redis2.NewJobBroker(client, keyBuilder, systemClock)
	queueRepo := redis2.NewQueueRepo(client, keyBuilder)
	jobRepo := redis2.NewJobRepo(client, keyBuilder, systemClock)
	logLevel := config.GetLogLevel(cfg)
	slogLogger := provideSlogLogger(logLevel)
	processorConfig := config.GetProcessorConfig(cfg)
	jobProcessorService := processor.NewJobProcessorService(registry, jobBroker, jobRepo, recorder, systemClock, slogLogger, processorConfig)
	randomGenerator := uid.NewRandomGenerator()
	poolConfig := config.GetWorkerPoolConfig(cfg)
	pool := worker.NewPool(jobBroker, queueRepo, jobProcessorService, recorder, randomGenerator, slogLogger, poolConfig)
	return pool
}

// InjectScheduler builds the periodic sweep graph.
func InjectScheduler(cfg *config.AppConfig, client redis.UniversalClient, recorder metrics.Recorder) *scheduler.Scheduler {
	redisNamespace := config.GetRedisNamespace(cfg)
	keyBuilder := provideKeyBuilder(redisNamespace)
	systemClock := clock.NewSystemClock()
	jobBroker := redis2.NewJobBroker(client, keyBuilder, systemClock)
	jobRepo := redis2.NewJobRepo(client, keyBuilder, systemClock)
	queueRepo := redis2.NewQueueRepo(client, keyBuilder)
	logLevel := config.GetLogLevel(cfg)
	slogLogger := provideSlogLogger(logLevel)
	schedulerConfig := config.GetSchedulerConfig(cfg)
	schedulerScheduler := scheduler.NewScheduler(jobBroker, jobRepo, queueRepo, recorder, systemClock, slogLogger, schedulerConfig)
	return schedulerScheduler
}

// InjectHandlerRegistry builds the task handler registry.
//
// It is injected once and shared by the worker pool and the readiness endpoint,
// so both agree on what this process can actually run.
func InjectHandlerRegistry() services.IHandlerRegistry {
	handlerRegistry := processor.NewHandlerRegistry()
	return handlerRegistry
}

// wire.go:

var clockSet = wire.NewSet(clock.NewSystemClock, wire.Bind(new(clock.Clock), new(*clock.SystemClock)))

var uidSet = wire.NewSet(uid.NewRandomGenerator, wire.Bind(new(uid.Generator), new(*uid.RandomGenerator)))

var loggerSet = wire.NewSet(config.GetLogLevel, provideSlogLogger, wire.Bind(new(logger.Logger), new(*logger.SlogLogger)))

// metricsSet binds the recorder and adapts *prom.Registry to the narrower
// prom.Registerer that NewRecorder accepts. The narrowing is intentional: the
// recorder only registers collectors, so it should not be handed a type that
// can also gather them.
var metricsSet = wire.NewSet(
	provideRegisterer, prometheus2.NewRecorder, wire.Bind(new(metrics.Recorder), new(*prometheus2.Recorder)),
)

var keyBuilderSet = wire.NewSet(config.GetRedisNamespace, provideKeyBuilder)

var jobRepoSet = wire.NewSet(redis2.NewJobRepo, wire.Bind(new(persistence.IJobRepo), new(*redis2.JobRepo)))

var jobBrokerSet = wire.NewSet(redis2.NewJobBroker, wire.Bind(new(persistence.IJobBroker), new(*redis2.JobBroker)))

var queueRepoSet = wire.NewSet(redis2.NewQueueRepo, wire.Bind(new(persistence.IQueueRepo), new(*redis2.QueueRepo)))

var idempotencySet = wire.NewSet(redis2.NewIdempotencyStore, wire.Bind(new(persistence.IIdempotencyStore), new(*redis2.IdempotencyStore)))

// persistenceSet is every storage port bound to its Redis implementation.
var persistenceSet = wire.NewSet(
	keyBuilderSet,
	jobRepoSet,
	jobBrokerSet,
	queueRepoSet,
	idempotencySet,
)

var handlerRegistrySet = wire.NewSet(processor.NewHandlerRegistry, wire.Bind(new(services.IHandlerRegistry), new(*processor.HandlerRegistry)))

var enqueuerSet = wire.NewSet(config.GetEnqueuerConfig, enqueuer.NewEnqueuerService, wire.Bind(new(services.IEnqueuerService), new(*enqueuer.EnqueuerService)))

var inspectorSet = wire.NewSet(inspector.NewInspectorService, wire.Bind(new(services.IInspectorService), new(*inspector.InspectorService)))

var processorSet = wire.NewSet(config.GetProcessorConfig, processor.NewJobProcessorService, wire.Bind(new(services.IJobProcessorService), new(*processor.JobProcessorService)))
